### ISSUE TITLE
wrong url format

### ISSUE THREAD

**Issue by Morriz** [Auoja/node-slack#1]
I now get 404's. You should check the documentation for the correct webhook format:

https://hooks.slack.com/services/9charsKey/9charsKey/someLongerKey

But maybe I am totally mistaken here?

**Comment by Morriz** [comment]
I would suggest just asking for params.url to be the correct webhook url, instead of team/token combo

**Comment by Auoja** [comment]
Yes, that might be a good idea. Certainly more future proof.
